import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/globals.css'
import Appbar from "@/components/appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex w-full flex-col h-full "}>
      <Appbar/>

      {children}
      </body>
    </html>
  );
}
